logging:
  level:
    root: ERROR
    org.springframework.cloud.gateway: WARN
    org.springframework.cloud.loadbalancer: WARN
    org.springframework: WARN
    liquibase: INFO


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: Hikari
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 50
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        userServerPrepStmts: true
      validation-timeout: 300000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: pm
        jdbc:
          batch-size: 50
        order-inserts: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    contexts: local

server:
  port: 8080
