version: '3.8'
services:
  db-profile-matcher:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pm
    ports:
      - '5432:5432'
    volumes:
      - db-profile-matcher:/var/lib/postgresql/data

volumes:
  db-profile-matcher:
    driver: local
